### ISSUE TITLE
Still Active?

### ISSUE THREAD

**Issue by danperks** [lbrndnr/SoundCloud#3]
Hey @lbrndnr 

I'm currently attempting to make a multi-platform music app, so you can play Spotify and Soundcloud songs in the same app.
For Spotify, they have an SDK that I can use to tell the real Spotify app to play songs in the background, but Soundcloud has no such option.

I'm basically wondering if, at best you are still maintaining this package or, at worst, you are active on GitHub at all.
If so, I'll likely give a good go at contributing where I can to keeping this package functional in the future.
Similarly to you, I'll have a project of my own this would be used in as motivation :)

As long as you are either working on this when you can, or at least able to merge changes in and so on, I'll give this package a try!

Thanks

**Comment by lbrndnr** [comment]
Hi,
I'm still using Nuage, the client I built around this API, but not really maintaining it anymore. There's [something similar](https://github.com/lbrndnr/nuage-macos/blob/main/Nuage/Audio/StreamPlayer.swift) to what you need in that project though, so make sure to check it out. 

I'm definitely willing to merge in the changes if you have any! :)

**Comment by danperks** [comment]
That linked file is not a million miles away from my own setup, I've got these modular "controllers" that just override a set of common methods, and can bubble up an event to the master controller if their data changes. That should make life a bunch easier.

I'll have a go at implementing this next week and will try to fix anything that I find broken in the process.

Thanks 👍

**Comment by lbrndnr** [comment]
Closing this for now :)
